version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme  # Définit un mot de passe pour l'utilisateur elastic
      - xpack.security.enabled=false  # Désactive la sécurité pour les tests
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0  
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic  # Utilisateur par défaut
      - ELASTICSEARCH_PASSWORD=changeme  # Mot de passe défini ci-dessus
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic_network

volumes:
  esdata:
    driver: local

networks:
  elastic_network:  # Création d'un réseau pour les services
