name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r belib-pipeline/requirements.txt
        pip install kedro

    - name: Check Kedro version
      run: kedro --version

    - name: Run Kedro pipeline
      run: |
        cd belib-pipeline  # Naviguez vers le répertoire du projet Kedro
        kedro run
