name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pre-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r belib-pipeline/requirements-pyarrow.txt

    - name: Install remaining dependencies
      run: |
        pip install -r belib-pipeline/requirements.txt

    - name: Run Kedro pipeline
      run: |
        kedro install
        kedro run
